spring:
  application:
    name: ${person.gw.name}

  security:
    user:
      name: ${person.gw.security-user-name}
      password: ${person.gw.security-user-password}

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: ${person.cud.context}
            uri: ${person.cud.uri}
            predicates:
            - Path=/api/people-${person.cud.context}/**
            filters:
            - SetRequestHeader=Authorization, ${person.cud.security-auth}

          - id: ${person.query.context}
            uri: ${person.query.uri}
            predicates:
            - Path=/api/people-${person.query.context}/**
            filters:
            - SetRequestHeader=Authorization, ${person.query.security-auth}

          default-filters:
          - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health

logging:
  pattern:
    correlation: ${person.logging-pattern-correlation}

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: ${person.swagger-enabled}
  api-docs:
    enabled: ${person.swagger-enabled}

server:
  port: ${person.gw.port}